-- (2) Diga por que o código abaixo é inválido:
-- [[1,2],3,[4,5]]
-- (R): O Haskell é uma linguagem fortemente tipada, o que significa que um dado deve seguir a uma estrutura rígida. No caso, o dado é uma lista
-- (R'): de listas, mas o segundo elemento não é uma lista, e sim um Number, inválidando a tipagem do dado.